# Generated by Django 5.1.7 on 2025-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_taxon', models.IntegerField(verbose_name='ID Taxon')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('nom_vernaculaire', models.CharField(max_length=100, verbose_name='Nom Vernaculaire')),
                ('nom_scientifique', models.CharField(max_length=100, verbose_name='Nom Scientifique')),
                ('categorie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Catégorie')),
                ('id_ref', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Référence')),
                ('recommandation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recommandation')),
                ('position', models.CharField(blank=True, max_length=10, null=True, verbose_name='Position')),
                ('alternative', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alternative')),
                ('date_mise_a_jour', models.DateField(verbose_name='Date de Mise à Jour')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
            },
        ),
    ]
